### PR TITLE
Removed htmlelements-matchers. Resolves #69.

### LINKED ISSUE #69: Remove matchers module
Now matchers in separate project:
https://github.com/yandex-qatools/matchers-java

### PR DESCRIPTION
**Pull request by ham1**
- [ ] Check if any changes here need to be merged into https://github.com/yandex-qatools/matchers-java

### CODE REVIEW

**Comment by ham1** [comment]
Is this still valid and worth fixing merge issues or should this and #69 be closed?

**Comment by artkoshelev** [comment]
Yep, it's still valid

**Comment by ham1** [comment]
Updated PR, can this be merged or is there something which needs merging into https://github.com/yandex-qatools/matchers-java ?

**Comment by artkoshelev** [comment]
@lanwen @leonsabr any objections?

**Comment by lanwen** [comment]
I think it should be leaved as is. @eroshenkoam  have a beta of new version in  a separate repo

**Pull request closed without merging**
