### PR TITLE
Some refactoring depends on new selenium-java version

### PR DESCRIPTION
**Pull request by emaks**

### CODE REVIEW

**Comment by artkoshelev** [comment]
hi, thank you for this pr, this is exactly what i planned to do :) there are significant changes here, so i need some time to review it carefully. please take a look at failed test and fix tabs/spaces indentation (most of them are in changed xml files)

**Comment by emaks** [comment]
Test is failed because AjaxElementLocator class was removed and there is no [these] (https://github.com/yandex-qatools/htmlelements/commit/e63911f821fbf85466908c78e93437b0312a04b5#diff-5eb9d11ca0350a93f8e91aea8e79fe08L74) changes. Should I delete this test? What do you think?

**Comment by emaks** [comment]
> fix tabs/spaces indentation (most of them are in changed xml files)
indents made with tab are replaced by spaces in xml files :)

**Comment by artkoshelev** [comment]
Yep, i think we should delete this test and propose corresponding changes to selenium project

**Comment by lanwen** [comment]
@emaks please can you write in PR description list of main changes please? (To simplify changelog generation)

**Pull request merged**
