### PR TITLE
#158 Added supporting Selenium 4

### PR DESCRIPTION
**Pull request by 0I0u3uk**
#158 Added supporting Selenium 4

### CODE REVIEW

**Comment by 0I0u3uk** [comment]
@artkoshelev hi!
Can you check and merge my pr if everything is alright?

**Comment by artkoshelev** [comment]
LGTM, thanks!

**Comment by user-135217** [comment]
When 1.21.0 release can be expected? Looks like all required changes already merged...

**Comment by natalyurikh** [comment]
@artkoshelev  Hi, there is a test that need to be fixed as well, UsingSelectTest
 `(when(countryBoxElement.getDomAttribute("multiple")).thenReturn("true");)`
I am also wondering about **1.21.0** release date.

**Comment by artkoshelev** [comment]
Sorry, i don't know if release pipelines are still working and where they are at all =). Let's see if @eroshenkoam is around and could help.

**Pull request merged**
