### PR TITLE
Java 8 upgrade

### PR DESCRIPTION
**Pull request by ham1**
As discussed in #96

### CODE REVIEW

**Comment by ham1** [comment]
Sorry, also included my failing test for #95 as I didn't branch for that one and then included that in this commit. Hope this isn't too confusing, I can try to fix if that would help.

**Comment by ham1** [comment]
Closing due to messing up branching. Will try again.

**Comment by lanwen** [comment]
@ham1 You can just rewrite remote branch with force push, it updates PRs automatically

**Comment by ham1** [comment]
Ah, ok, thanks for the info.

**Pull request closed without merging**
