### PR TITLE
remove hardcoded implicitlywait

### PR DESCRIPTION
**Pull request by Kuhtich**
Added ability to pass implicitlywait timeout for HtmlElements

### CODE REVIEW

**Comment by akrambek** [comment]
Is it going to be merge anytime soon?

**Comment by artkoshelev** [comment]
@akrambek as you can see, there are few bits need to be fixed first, so you can do this in case you interested in this PR

**Comment by akrambek** [comment]
@artkoshelev thank I will take a look. In turn out that the issue I was facing was not due to timeout.

**Comment by artkoshelev** [comment]
done [here](https://github.com/yandex-qatools/htmlelements/pull/82)

**Pull request closed without merging**
