### PR TITLE
Expect StaleElementReferenceException on getText

### PR DESCRIPTION
**Pull request by clicman**
This test always fails. Seems missed exception expectation. Now we expect it.

### CODE REVIEW

**Comment by clicman** [comment]
This is very strange. On my environment mvn clean test fails with StaleElementReferenceException if I not expect it. But on your ci environment exception isn't thrown and my PR fails to test. 
Any ideas?
As I can see mock configured to throw this exception.

**Comment by clicman** [comment]
Another strange thing. I've gave it to test to two my colleguas. One got exception another one - not. 
I'm confised.

**Comment by clicman** [comment]
Redisigned test. Now it works as expected on all environments.

**Comment by artkoshelev** [comment]
There shouldn't be stale element exception when using htmlelements. If exception occurs, framework re-search required element. This test was designed to check this behavior. Get some investigation why it fails on your env.

**Pull request closed without merging**
